# Site settings
title: Sociocracy 3.0 Patterns Repository
email: bernhard.bockelbrink@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The canonical list and definitions of Sociocracy 3.0 patterns, maintained by Bernhard Bockelbrink and James Priest.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://s3-working-group.github.io/s3patterns"
twitter_username: sociocracy30

# Build settings
source:   .
destination:  ./_site
layouts_dir:  ./_layouts
includes_dir: ./_includes


markdown: kramdown
safe: true # required on Github pages (no plugins)

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # overrides previous default layout


exclude:      [
  "build-handbook.sh", 
  "build-site.sh", 
  "generate-index-files.sh",
  "_python", "README.md",
  
  "all-patterns.md",
  "index--groups--toc.md",

  # auto-generated from here on:
  "alignment--content.md",
  "alignment--toc.md",
  "alignment--master.md",
  "bringing-in-s3-patterns--content.md",
  "bringing-in-s3-patterns--toc.md",
  "bringing-in-s3-patterns--master.md",
  "building-organizations--content.md",
  "building-organizations--toc.md",
  "building-organizations--master.md",
  "coordinating-work--content.md",
  "coordinating-work--toc.md",
  "coordinating-work--master.md",
  "effective-meetings--content.md",
  "effective-meetings--toc.md",
  "effective-meetings--master.md",
  "making-and-evolving-agreements--content.md",
  "making-and-evolving-agreements--toc.md",
  "making-and-evolving-agreements--master.md",
  "navigation--content.md",
  "navigation--toc.md",
  "navigation--master.md",
  "organizational-structure--content.md",
  "organizational-structure--toc.md",
  "organizational-structure--master.md",
  "roles--content.md",
  "roles--toc.md",
  "roles--master.md",]
